import { useState } from "react"
import type { FormEvent } from "react"
import { ShieldCheck } from "lucide-react"
import { toast } from "sonner"
import { OneTimeSecret } from "@/components/OneTimeSecret"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
export interface ClaimPanelProps { claiming:boolean; loginCode:string|null; onClaim:(orderNo:string)=>Promise<boolean>; onDismiss:()=>void; onLogin:(code:string)=>Promise<boolean> }
export function ClaimPanel({claiming,loginCode,onClaim,onDismiss,onLogin}:ClaimPanelProps){const[orderNo,setOrderNo]=useState("");async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!orderNo.trim()){toast.error("请输入订单号");return}if(await onClaim(orderNo))setOrderNo("")}if(loginCode)return <Card className="h-full animate-fade-in-up"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-5 text-emerald-600 dark:text-emerald-400"/>认领成功</CardTitle><CardDescription>登录码已生成，仅显示一次。</CardDescription></CardHeader><CardContent><OneTimeSecret title="登录码" value={loginCode} description="" warning="请保存好登录码，不要分享给他人。" action={{label:"立即登录",onClick:()=>onLogin(loginCode)}}/></CardContent><CardFooter><Button variant="ghost" size="sm" onClick={onDismiss}>认领其它订单</Button></CardFooter></Card>;return <Card className="h-full transition-shadow duration-300 hover:shadow-md"><CardHeader><CardTitle>认领订单</CardTitle><CardDescription>输入爱发电订单号，验证后即可开通账户。</CardDescription></CardHeader><form className="flex flex-1 flex-col" onSubmit={submit}><CardContent className="flex-1"><label className="grid gap-2" htmlFor="claim-order-no"><span className="text-sm font-medium">订单号</span><div className="flex gap-2"><Input className="min-w-0 flex-1" id="claim-order-no" value={orderNo} onChange={e=>setOrderNo(e.target.value)} placeholder="例如 2024xxxx" autoComplete="off"/><Button className="shrink-0" type="submit" disabled={claiming}>{claiming?"核验中…":"提交并核验"}</Button></div></label></CardContent></form></Card>}
