import { ExternalLink } from "lucide-react"
import { Button, buttonVariants } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog"
import { ThemeToggle } from "@/components/ThemeToggle"
import { SPONSOR_URL } from "@/lib/constants"
import { cn } from "@/lib/utils"
export interface HeaderProps { authenticated:boolean; activeTab:"overview"|"api-key"; onTabChange:(tab:"overview"|"api-key")=>void; onLogout:()=>void }
export function Header({authenticated,activeTab,onTabChange,onLogout}:HeaderProps){return <header className="sticky top-0 z-20 border-b bg-background/80 backdrop-blur-md"><div className="mx-auto flex h-14 max-w-6xl items-center justify-between gap-3 px-4 sm:gap-6 sm:px-6 lg:px-8"><div className="flex min-w-0 items-center gap-2.5"><img src="/axoyellow.png" alt="Axolotl" className="size-8 shrink-0 object-contain"/><span className="truncate text-sm font-semibold tracking-tight">Axolotl Sponsor</span></div>{authenticated&&<Tabs value={activeTab} onValueChange={value=>onTabChange(value as "overview"|"api-key")} className="hidden sm:flex"><TabsList variant="line" className="gap-1"><TabsTrigger value="overview" className="px-3">概览</TabsTrigger><TabsTrigger value="api-key" className="px-3">API Key</TabsTrigger></TabsList></Tabs>}<div className="flex shrink-0 items-center gap-1.5 sm:gap-2"><ThemeToggle/><a className={cn(buttonVariants({variant:"outline",size:"sm"}))} href={SPONSOR_URL} target="_blank" rel="noreferrer"><span className="hidden sm:inline">爱发电支持</span><span className="sm:hidden">支持</span><ExternalLink data-icon="inline-end"/></a>{authenticated&&<AlertDialog><AlertDialogTrigger render={<Button variant="ghost" size="sm"/>}>退出</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>退出登录？</AlertDialogTitle><AlertDialogDescription>退出后需要重新输入登录码。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={onLogout}>确认退出</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}</div></div>{authenticated&&<div className="mx-auto block max-w-6xl px-4 pb-2 sm:hidden"><Tabs value={activeTab} onValueChange={value=>onTabChange(value as "overview"|"api-key")}><TabsList variant="line" className="w-full justify-start"><TabsTrigger value="overview" className="px-3">概览</TabsTrigger><TabsTrigger value="api-key" className="px-3">API Key</TabsTrigger></TabsList></Tabs></div>}</header>}
