import { BarChart3 } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { useUsage } from "@/hooks/useUsage"

const DEEPL_RATE = 25
const WEEKDAYS = ["周日", "", "周二", "", "周四", "", "周六"]
function formatChars(value:number){return value>=1000000?(value/1000000).toFixed(2)+"M":value>=1000?(value/1000).toFixed(1)+"K":String(value)}
function levelFor(chars:number){if(!chars)return 0;if(chars>12000)return 4;if(chars>9000)return 3;if(chars>6000)return 2;return 1}
function dateValue(date:string){return new Date(date+"T00:00:00")}
export function UsageHeatmap(){
 const{data,loading}=useUsage()
 if(loading)return <Card><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="size-5"/>用量</CardTitle></CardHeader><CardContent><div className="h-36 animate-pulse rounded-xl bg-muted"/></CardContent></Card>
 if(!data)return null
 const first=dateValue(data.days[0]?.date??new Date().toISOString().slice(0,10));const start=new Date(first);start.setDate(first.getDate()-first.getDay())
 const cells=Array.from({length:13*7},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);const key=date.toISOString().slice(0,10);const day=data.days.find(item=>item.date===key);return{date,day,level:levelFor(day?.input_chars??0)}})
 const weeks=Array.from({length:13},(_,index)=>cells.slice(index*7,index*7+7));const equivalent=data.total_input_chars/1000000*DEEPL_RATE
 return <Card className="animate-fade-in"><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="size-5"/>用量</CardTitle></CardHeader><CardContent className="grid gap-5"><div className="grid grid-cols-2 gap-4 sm:grid-cols-4"><div><p className="text-2xl font-semibold tracking-tight">{formatChars(data.total_input_chars)}</p><p className="mt-1 text-xs text-muted-foreground">字符 / 近 12 周</p></div><div><p className="text-2xl font-semibold tracking-tight">{data.total_request_count.toLocaleString()}</p><p className="mt-1 text-xs text-muted-foreground">请求次数</p></div><div><p className="text-2xl font-semibold tracking-tight">${equivalent.toFixed(2)}</p><p className="mt-1 text-xs text-muted-foreground">DeepL 等效价</p></div><div><p className="text-2xl font-semibold tracking-tight">{data.total_error_count}</p><p className="mt-1 text-xs text-muted-foreground">错误次数</p></div></div><div className="overflow-x-auto pb-1"><div className="grid min-w-[620px] grid-cols-[34px_1fr] gap-x-2"><div/><div className="grid grid-cols-[repeat(13,minmax(0,1fr))] gap-1 text-[10px] text-muted-foreground">{weeks.map((week,index)=>{const month=week.find(cell=>cell.date.getDate()<=7);return <span key={index} className="truncate">{month?month.date.toLocaleString("zh-CN",{month:"short"}):""}</span>})}</div><div className="grid grid-rows-7 gap-1 text-[10px] text-muted-foreground">{WEEKDAYS.map((label,index)=><span key={index} className="flex h-3 items-center">{label}</span>)}</div><div className="grid grid-flow-col grid-rows-7 grid-cols-[repeat(13,minmax(0,1fr))] gap-1 rounded-lg border bg-muted/20 p-3">{cells.map(cell=><span key={cell.date.toISOString()} title={cell.day?cell.day.date+" · "+formatChars(cell.day.input_chars)+" 字符 · "+cell.day.request_count+" 次请求":cell.date.toISOString().slice(0,10)+" · 暂无用量"} className={"size-3 rounded-[3px] bg-heat-"+cell.level+" transition-transform duration-150 hover:scale-125"} aria-label={cell.day?cell.day.date+" "+cell.day.input_chars+" 字符":"暂无用量"}/>)}</div></div></div><div className="flex items-center justify-end gap-1 text-[11px] text-muted-foreground">少 <span className="mx-1 inline-flex gap-1">{[0,1,2,3,4].map(level=><i key={level} className={"size-3 rounded-[3px] bg-heat-"+level}/>)}</span>多</div></CardContent></Card>
}
