import type { ApiErrorBody, ApiKeyResponse, ClaimResponse, LoginResponse, MeResponse, UsageResponse } from "./types"
const API_BASE=import.meta.env.VITE_API_ORIGIN??(import.meta.env.DEV?"/sponsor":"https://api.axlmc.org")
const LOCAL_MOCK=import.meta.env.DEV&&import.meta.env.VITE_USE_REAL_API!=="true"
export class ApiError extends Error { readonly code:string; readonly status:number; readonly requestId?:string; constructor(code:string,status:number,message:string,requestId?:string){super(message);this.name="ApiError";this.code=code;this.status=status;this.requestId=requestId} }
const ERROR_MESSAGES:Record<string,string>={UNAUTHENTICATED:"登录已失效，请重新登录",INVALID_LOGIN_CODE:"登录码无效或已被吊销",INVALID_ORDER:"订单号格式不正确",ORDER_VERIFICATION_FAILED:"订单无法核验，请确认订单号属于 Axolotl 且已支付成功",SPONSORSHIP_REQUIRED:"尚未达到 ¥9.90 永久开通门槛",RATE_LIMITED:"操作过于频繁，请稍后再试",SERVICE_UNAVAILABLE:"赞助者服务暂时不可用，请稍后重试"}
export const NETWORK_ERROR_MESSAGE="暂时无法连接赞助者服务，请检查网络后重试"
export function errorMessage(error:unknown){return error instanceof ApiError?ERROR_MESSAGES[error.code]??error.message:NETWORK_ERROR_MESSAGE}
function mockMe():MeResponse{return{lifetime_paid_fen:990,entitlement_status:"granted",threshold_fen:990}}
function mockUsage():UsageResponse{const days=[];const now=new Date();for(let i=364;i>=0;i--){const date=new Date(now);date.setDate(now.getDate()-i);const wave=(i*17)%71;const dateKey=date.getFullYear()+"-"+String(date.getMonth()+1).padStart(2,"0")+"-"+String(date.getDate()).padStart(2,"0");days.push({date:dateKey,request_count:18+wave,input_chars:4200+wave*163,error_count:i%19===0?1:0})}return{days,total_request_count:days.reduce((n,d)=>n+d.request_count,0),total_input_chars:days.reduce((n,d)=>n+d.input_chars,0),total_error_count:days.reduce((n,d)=>n+d.error_count,0)}}
async function mockRequest<T>(path:string,init?:RequestInit):Promise<T>{const method=init?.method??"GET";if(path==="/me"){if(localStorage.getItem("sponsor_mock_session")==="0")throw new ApiError("UNAUTHENTICATED",401,"login required");localStorage.setItem("sponsor_mock_session","1");return mockMe() as T}if(path==="/me/usage")return mockUsage() as T;if(path==="/auth/recovery-login"&&method==="POST"){localStorage.setItem("sponsor_mock_session","1");return{status:"authenticated"} as T}if(path==="/afdian/claim"&&method==="POST")return{login_code:"axl_login_demo_7f3a9c",message:"mock"} as T;if(path==="/me/api-key"&&method==="POST")return{api_key:"axl_live_demo_7f3a9c",message:"mock"} as T;if(path==="/me/api-key"&&method==="DELETE")return undefined as T;throw new ApiError("NOT_FOUND",404,"mock endpoint not found")}
async function request<T>(path:string,init?:RequestInit):Promise<T>{if(LOCAL_MOCK)return mockRequest<T>(path,init);let response:Response;try{response=await fetch(`${API_BASE}${path}`,{credentials:"include",headers:{"Content-Type":"application/json",...init?.headers},...init})}catch{throw new ApiError("NETWORK_ERROR",0,NETWORK_ERROR_MESSAGE)}if(response.status===204)return undefined as T;const body:unknown=await response.json().catch(()=>null);if(!response.ok){const error=(body as ApiErrorBody|null)??{code:"UNKNOWN",message:`请求失败（HTTP ${response.status}）`};throw new ApiError(error.code,response.status,error.message,error.request_id)}return body as T}
export const api={me:()=>request<MeResponse>("/me"),usage:()=>request<UsageResponse>("/me/usage"),claim:(orderNo:string)=>request<ClaimResponse>("/afdian/claim",{method:"POST",body:JSON.stringify({order_no:orderNo})}),login:(loginCode:string)=>request<LoginResponse>("/auth/recovery-login",{method:"POST",body:JSON.stringify({login_code:loginCode})}),generateApiKey:()=>request<ApiKeyResponse>("/me/api-key",{method:"POST"}),revokeApiKey:()=>request<void>("/me/api-key",{method:"DELETE"})}
